# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
    lane :deploy do

    gradle_file = 'app/build.gradle.kts'

    version_name = android_get_version_name(gradle_file: gradle_file)

    latest_version_code = google_play_track_version_codes(track: 'internal').max
    android_set_version_code(gradle_file: gradle_file, version_code: latest_version_code + 1)

    gradle(task: "clean bundleRelease")

    version_text = "#{latest_version_code + 1} (#{version_name})"

    upload_to_play_store(
     track: 'internal',
     version_name: version_text,
     mapping_paths: [
        'app/build/outputs/mapping/release/mapping.txt'
     ]
    )
    end
end
